experimental_monorepo_root = true

[env]
MISE_EXPERIMENTAL=1

# For now define tools in the monorepo. As time passes and new versions come out, it will be necessary to move to subfolders
[tools]
python = "3.14.0"
cmake = "4.2.0"
rust = "1.91.1"
zig = "0.15.2"
elixir = "latest"
go = "latest"

