[tasks.configure]
run = """
chmod +x ./part-one.sh
chmod +x ./part-two.sh
"""


[tasks.default]
depends = ["configure"]
run = """
echo "Part One"
./part-one.sh < inputs/main.txt
echo "Part Two"
./part-two.sh < inputs/main.txt
"""

[tasks.one]
run = "./part-one.sh < inputs/main.txt"

[tasks.two]
run = "./part-two.sh < inputs/main.txt"
